server:
  port: 18080
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    livereload:
      port: 34521
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 300000
    database: 1
    jedis:
      pool:
        max-idle: 10
        min-idle: 2
        max-wait: -1
        max-active: 8
        time-between-eviction-runs: 100000
