server:
  port: 18080
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    livereload:
      port: 34521
  redis:
    host: localhost
    port: 6379
    password: 123456
