## 单机配置
#singleServerConfig:
#  address: "redis://localhost:6379"
#  password: 123456
#  clientName: null
#  database: 7 #选择使用哪个数据库0~15
#  idleConnectionTimeout: 10000
#  pingTimeout: 1000
#  connectTimeout: 10000
#  timeout: 3000
#  retryAttempts: 3
#  retryInterval: 1500
#  reconnectionTimeout: 3000
#  failedAttempts: 3
#  subscriptionsPerConnection: 5
#  subscriptionConnectionMinimumIdleSize: 1
#  subscriptionConnectionPoolSize: 50
#  connectionMinimumIdleSize: 32
#  connectionPoolSize: 64
#  dnsMonitoringInterval: 5000
#  #dnsMonitoring: false
#
#threads: 0
#nettyThreads: 0
#codec:
#  class: "org.redisson.codec.JsonJacksonCodec"
#transportMode: "NIO"
#
## 集群配置
##clusterServersConfig:
##  idleConnectionTimeout: 10000
##  pingTimeout: 1000
##  connectTimeout: 10000
##  timeout: 3000
##  retryAttempts: 3
##  retryInterval: 1500
##  reconnectionTimeout: 3000
##  failedAttempts: 3
##  password: null
##  subscriptionsPerConnection: 5
##  clientName: null
##  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
##  slaveSubscriptionConnectionMinimumIdleSize: 1
##  slaveSubscriptionConnectionPoolSize: 50
##  slaveConnectionMinimumIdleSize: 10
##  slaveConnectionPoolSize: 64
##  masterConnectionMinimumIdleSize: 10
##  masterConnectionPoolSize: 64
##  readMode: "SLAVE"
##  nodeAddresses:
##    - "redis://192.168.254.141:6379"
##  scanInterval: 1000
##threads: 0
##nettyThreads: 0
##codec: !<org.redisson.codec.JsonJacksonCodec> {}
##useLinuxNativeEpoll: false
